#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias x='exit'
alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'

eval "$(fasd --init auto)"
#fasd aliases
alias v='f -e vim'
alias gitpurge='git branch --merged | grep -Ev "(\*|master|develop|staging)" | xargs -n 1 git branch -d'

export PATH=$PATH\:/Users/spritchard/Library/Python/3.6/bin
